/**
 * Emoji Service
 *
 * Provides Discord emoji strings for FFXIV dyes.
 * Emojis are uploaded as Application Emojis and referenced by ID.
 */

// Import emoji mapping generated by upload-emojis.ts script
import emojiMapping from '../data/emoji-mapping.json';

// Type the mapping as Record<string, string> (itemID -> emoji string)
const mapping = emojiMapping as Record<string, string>;

/**
 * Get Discord emoji string for a dye by its item ID
 * @returns Emoji string like "<:dalamud_red:1234567890>" or undefined if not found
 */
export function getDyeEmoji(itemId: number): string | undefined {
  return mapping[String(itemId)];
}

/**
 * Get Discord emoji string for a dye, with fallback to a colored square
 * @returns Emoji string or fallback
 */
export function getDyeEmojiOrFallback(itemId: number, hex?: string): string {
  const emoji = getDyeEmoji(itemId);
  if (emoji) return emoji;

  // Fallback: use a colored circle emoji based on hue (rough approximation)
  // This shouldn't happen for normal dyes, but handles edge cases
  return '🎨';
}

/**
 * Check if emoji mapping is available for a dye
 */
export function hasDyeEmoji(itemId: number): boolean {
  return String(itemId) in mapping;
}

/**
 * Get total count of available emoji mappings
 */
export function getEmojiCount(): number {
  return Object.keys(mapping).length;
}
